- src/main/java/synergy/comegongbang/domain/member/controller/MemberController.java
- src/main/java/synergy/comegongbang/domain/member/model/entity/Member.java
- src/main/java/synergy/comegongbang/domain/member/model/request/MemberLoginReq.java
- src/main/java/synergy/comegongbang/domain/member/model/request/MemberSignupReq.java
- src/main/java/synergy/comegongbang/domain/member/model/response/MemberSignupRes.java
- src/main/java/synergy/comegongbang/domain/member/repository/MemberRepository.java
- src/main/java/synergy/comegongbang/domain/member/service/MemberService.java
- 패키지/클래스명 컨벤션을 위한 보일러플레이트 코드 작성
<br><br>
<br><br>
팀원간 회의를 통해 정한 패키지 구조 컨벤션을 통해 보일러플레이트를 만들어놨습니다.
팀원들은 모두 해당 폴더구조와 클래스 명명을 지켜주시기 바랍니다. 
<br><br>
<br><br>
> [Style] 패키지/클래스명 컨벤션을 위한 보일러플레이트

- frontend/package-lock.json
- frontend/package.json
- frontend/src/main.js
- frontend/src/router/index.js
- pinia 세팅
- router 세팅
<br><br>
<br><br>
git clone 하고 vue 실행 
npm run serve
만일  (Module not found: Error: Can't resolve) 에러가 터지면
다음 4개 모듈 다운로드 
npm install vue
npm install router
npm install pinia
npm install pinia-plugin-persistedstate
일련의 과정 수행하시면 됩니다~
<br><br>
<br><br>
> [Init] frontend 보일러 플레이트 세팅 - pinia , router 세팅 추가

- frontend/src/pages/member/LoginPage.vue
- frontend/src/stores/useMemberStore.js
- frontend/vue.config.js
-axios 미설정
-페이지 디자인 구현 및 store에 잘 들어가는지 확인
#48 
- HTML , CSS 적용 확인
- v-model 안에 들어온 정보를 memberStore까지 잘 전달되는지 까지 확인
<br><br>
백엔드 api 개발이 완료되면 axios 연결 테스트까지 완료해야합니다! 
따라서 이슈는 닫지 않겠습니다.
<br><br>
vue.config.js 파일을 수정해서 , 프록시 설정 및 포트번호 설정을 추가했습니다! 
pull 받아서, 추후 axios 로 요청을 보낼 때 /api/{백엔드주소} 로 요청을 날리면 됩니다.
<br><br>
<br><br>
> [Feat] 로그인 페이지 구현 

- backend/src/main/java/com/synergy/backend/global/jwt/JwtFilter.java
- backend/src/main/java/com/synergy/backend/global/jwt/JwtUtil.java
- backend/src/main/java/com/synergy/backend/global/security/CustomUserDetailService.java
- backend/src/main/java/com/synergy/backend/global/security/CustomUserDetails.java
- backend/src/main/java/com/synergy/backend/global/security/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/filter/LoginFilter.java
- backend/src/main/java/com/synergy/backend/member/model/entity/Member.java
- backend/src/main/java/com/synergy/backend/member/model/request/MemberLoginReq.java
- backend/src/main/java/com/synergy/backend/member/repository/MemberRepository.java
#4 
- Security 추가 및 일반 로그인 기능 추가
- Jwt 추가 및 쿠키로 전달하도록 구현
<br><br>
- 로그인 요청이 성공 시, JToken 의 명명으로 토큰을 쿠키로 전달하도록 설정하였습니다. 
- HttpOnly 설정을 걸었기 때문에, 클라이언트측에서 javascript 로 쿠키를 꺼내올 수 없으며, 서버에게 요청을 보낼 때에도 withCredential을 통해서 전달 해야합니다.
HttpOnly 설정
withCredential 을 통한 쿠키 요청이 날라오면 쿠키를 꺼내오는 과정
<br><br>
<br><br>
<br><br>
> [Feat] 회원 로그인 기능 구현

- backend/src/main/java/com/synergy/backend/global/security/SecurityConfig.java
#8 
- 로그아웃 기능 구현
<br><br>
Spring-Securty 를 통해 /logout 요청이 들어오면 쿠키를 삭제하도록 구현하였습니다.
<br><br>
<br><br>
<br><br>
> [Feat] 회원 로그아웃 기능 구현

- backend/docker.compose.yml
#87 
- mariadb 도커 컴포즈 파일 작성
<br><br>
- 팀원 모두가 같은 db 환경에서 테스트 할 수 있도록 도커 컴포즈 파일을 작성했습니다.
- 도커 컴포즈 파일을 실행시키기만 하면 컨테이너가 실행됩니다.
- 아직 볼륨설정은 필요 없는 것으로 판단되어 하지 않았습니다.
<br><br>
환경 변수 처리가 필요해서 해당 pr 이후 환경변수 처리 후에 다시 pr 올리겠습니다.
<br><br>
<br><br>
> [Add]docker compose yml파일(mariadb) 추가

- frontend/package-lock.json
- frontend/src/components/product/ProductComponent.vue
- frontend/src/components/product/ProductListComponent.vue
- frontend/src/stores/useProductStore.js
#71 
- 이전에는 상품 리스트 컴포넌트에 더미 데이터를 넣어놨음
- axios와 연결해서 실제 데이터와 연결
<br><br>
- useProductStore 추가
- productListComponent에서 productStore에 저장된 실제 상품 목록인 productList를 사용
- 아직 product에서 직접적으로 가져올 수 있는 데이터만 가져왔습니다. (리뷰 수 등의 조인이 필요한 데이터는 아직 더미로만 넣어놨습니다.)
- 할인률도 아직 하드코딩 돼있습니다 
<br><br>
- 할인률에 대한 정확한 가이드가 필요해서 논의가 필요할 것 같습니다.
<br><br>
<br><br>
> [Feat]product-list 컴포넌트 axios 연결

- backend/src/main/java/com/synergy/backend/common/BaseResponseStatus.java
- backend/src/main/java/com/synergy/backend/config/JpaAuditingConfig.java
- backend/src/main/java/com/synergy/backend/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/orders/model/entity/Cart.java
- backend/src/main/java/com/synergy/backend/orders/model/entity/OptionInCart.java
- backend/src/main/java/com/synergy/backend/orders/model/request/AddCartReq.java
- backend/src/main/java/com/synergy/backend/orders/model/request/VerifyCartReq.java
- backend/src/main/java/com/synergy/backend/orders/model/response/AtelierListRes.java
- backend/src/main/java/com/synergy/backend/orders/model/response/CartDTO.java
- backend/src/main/java/com/synergy/backend/orders/model/response/CartRes.java
- backend/src/main/java/com/synergy/backend/orders/model/response/OptionListRes.java
- backend/src/main/java/com/synergy/backend/orders/model/response/ProductListRes.java
- backend/src/main/java/com/synergy/backend/orders/model/response/SubOptionsRes.java
- backend/src/main/java/com/synergy/backend/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/orders/repository/OptionInCartRepository.java
- backend/src/main/java/com/synergy/backend/orders/service/CartService.java
- backend/src/main/java/com/synergy/backend/product/model/entity/ProductSubOptions.java
#81 
장바구니 조회
장바구니 상품 선택 시 검증
<br><br>
**1. 장바구니의 상품을 조회**
장바구니에 상품을 저장할 땐 cart 테이블과 optionInCart 테이블로 구분해서 저장했습니다.
상품을 조회할 때는 공방 별, 상품 별, 같은 상품일 때 옵션 별로 그룹화하여 조회해아합니다.
그래서 5개의 dto를 계층구조로 만들어 반환합니다.
```
CartRes
AtelierListRes
ProductListRes
OptionListRes
SubOptionsRes
```
1. 우선 장바구니와 공방, 상품등을 조인하여 모든 상품의 정보를 리스트로 반환받습니다.
2. AtelierListRes를 Map 형태로 저장합니다. 그래서 같은 Atelier별로 중복되지 않게 저장했습니다.
3. 공방으로 map을 만들었으면 반복문을 돌면서 상품을 구분하며 저장합니다.
4. 상품을 먼저 구분하고, 옵션을 구분하고, 마지막으로 상세옵션(subOption)을 저장합니다.
5. 모든 상품이 저장되면 CartRes 응답 객체에 담아 반환해줍니다.
```json
{
"isSuccess": true,
"code": 1000,
"message": "요청에 성공하였습니다.",
"result": {
"atelierList": [
{
"atelierIdx": 1,
"atelierName": "공방1",
"productList": [
{
"productIdx": 1,
"cartIdx": 2,
"productName": "마카롱",
"count": 1,
"price": 1000,
"optionList": [
{ …
```
> [Feat] 장바구니 조회, 장바구니 선택 시 검증

- backend/src/main/java/com/synergy/backend/product/controller/ProductController.java
- backend/src/main/java/com/synergy/backend/product/querydsl/ProductRepositoryCustom.java
- backend/src/main/java/com/synergy/backend/product/querydsl/ProductRepositoryCustomImpl.java
- backend/src/main/java/com/synergy/backend/product/service/ProductService.java
#해당사항없음
- 상품 리스트 조회에 페이징 처리 추가
<br><br>
- 카테고리검색과 해시태그 검색 기능에 페이징 처리를 추가했습니다.
- 요청 보낼 때 page와 size도 paremeter로 전달해야합니다. 
요청 예시
```http://localhost:8080/search?categoryIdx=1&page=0&size=3```
<br><br>
<br><br>
<br><br>
> [Feat]상품 리스트 페이징 처리(#해당사항없음)

- frontend/src/pages/member/SingupPage.vue
- frontend/src/stores/useMemberStore.js
#99 
- 상품 리스트 무한 스크롤 구현
<br><br>
- 원래는 상품 리스트 컴포넌트를 메인 페이지의 캐러셀과 일반 상품 리스트 페이지에서 공용으로 사용하고자 했음
- 하지만 캐러셀은 무한 스크롤이 있으면 안되고, 일반 상품 리스트 페이지에서는 무한 스크롤이 구현돼야함.
- 따라서 캐러셀일 때와 일반 상품 리스트일 때의 리스트 컴포넌트를 구분함.
- 처음에는 v3-infinite-loading 플러그인을 사용해 구현했는데, 스크롤을 인식하지 못함
- Observer을 사용하는 방식으로 변경
- Observer 객체가 화면 하단위치에 올 경우 메서드를 호출하게 된다.
<br><br>
<br><br>
<br><br>
> [Feat]무한 스크롤 기능 구현(#99)

- frontend/src/pages/member/LoginPage.vue
#48 
- 로그인 페이지 내에 카카오 소셜 로그인 버튼 구현
<br><br>
<br><br>
네이버 소셜 버튼은 추후 반영하겠습니다!
<br><br>
<br><br>
> [Feat] 카카오 소셜 로그인 버튼 기능 추가 

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/product/CarouselComponent.vue
- frontend/src/components/product/CarouselProductListComponent.vue
- frontend/src/components/product/ObserverComponent.vue
- frontend/src/components/product/ProductListComponent.vue
- frontend/src/router/index.js
#99 
- 주석 정리
- 필요 없는 코드 삭제
<br><br>
- 필요없는 주석 또는 코드는 삭제함
- 개선 사항은 주석을 추가함
<br><br>
<br><br>
<br><br>
> [Style]무한 스크롤 기능 구현- 주석 정리(#99)

- backend/src/main/java/com/synergy/backend/domain/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Cart.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/UpdateCartCountReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
#124
장바구니 수량 조절(기존 increase, decrease api 2개 -> update api 1개)
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 장바구니 수량 조절 #124

- frontend/src/components/order/CartComponent.vue
- frontend/src/router/index.js
- frontend/src/stores/useCartStore.js
#127 
장바구니 페이지 만들었습니다.
수량 선택 및 상품 선택 가능
<br><br>
수량 선택 및 상품 선택 기능 
선택할 때 마다 새로 데이터를 받아오며, 수량을 변경할 때도 새로 데이터를 가져오고 
너무 딜레이 없이 수치가 변경돼서 로딩을 추가해서 데이터가 어느정도 변경됨을 보여줍니다. 
<br><br>
<br><br>
<br><br>
> [Feat] 장바구니 페이지 #127

- backend/src/main/java/com/synergy/backend/domain/orders/controller/PresentController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Orders.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/OrdersDetail.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Present.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/PresentProductRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/PresentRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/OrderRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/PresentRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/PresentService.java
- backend/src/main/java/com/synergy/backend/domain/product/model/dto/response/SearchProductRes.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/Product.java
#133 
- 내가 보낸 선물 리스트 조회
- 내가 받은 선물 리스트 조회
- fetch join 사용
- LAZY 처리
<br><br>
<br><br>
fetch join을 사용해도 presentService의 38번 라인에서 member 테이블을 조회하는데 이를 개선시키고 싶습니다.
<br><br>
<br><br>
> [Feat]선물(보낸,받은) 리스트 조회 기능 구현

- frontend/src/components/member/ChangeMemberInfoComponent.vue
- frontend/src/components/member/UpdateMemberInfoComponent.vue
- frontend/src/pages/member/LoginPage.vue
- frontend/src/pages/member/MemberInfoPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useMemberStore.js
#51 
- 최초 로그인 성공 시 스토어에 회원정보를 저장시켜, 사용할 수 있도록 구현
- 회원 수정 페이지 구현  -> 추후 컴포넌트끼리 조합 시켜야함 
- 회원 수정 part 컴포넌트 구현 
<br><br>
기존, api 마다 회원 정보를 불러온다는 점에서 한 페이지에 많은 DB 호출을 불러올 것을 감안하여,
최초 로그인 성공시에, 해당 유저의 유저 정보를 스토어 안에 저장시켜 다양한 공간에서 쓸 수 있도록 변경하였습니다.
<br><br>
<br><br>
<br><br>
> [Feat] 로그인 성공시 회원 정보를 스토어에 저장 할 수 있도록 구현 + 회원 수정 컴포넌트 구현

- backend/src/main/java/com/synergy/backend/domain/product/model/entity/Product.java
- backend/src/main/java/com/synergy/backend/domain/review/controller/ReviewController.java
- backend/src/main/java/com/synergy/backend/domain/review/model/entity/Review.java
- backend/src/main/java/com/synergy/backend/domain/review/model/request/CreateReviewReq.java
- backend/src/main/java/com/synergy/backend/domain/review/model/response/ReadDetailReviewRes.java
- backend/src/main/java/com/synergy/backend/domain/review/model/response/ReadListReviewRes.java
- backend/src/main/java/com/synergy/backend/domain/review/repository/ReviewRepository.java
- backend/src/main/java/com/synergy/backend/domain/review/service/ReviewService.java
- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
#104 #110 
- 이미지 업로드, 구매 검증 없이 상품 리뷰 작성 기능 구현
- 이미지 없는 리뷰 조회 기능 구현 (해당 상품의 리뷰 전체(리스트) 조회, 리뷰 상세 조회)
<br><br>
1. 이미지 업로드, 구매 검증 없이 상품 리뷰 작성
- 이미지 업로드, 구매 검증 없이 상품 리뷰를 작성하는 기능을 구현하였습니다.
- 구매 검증이 없기 때문에 회원과 상품을 existsById를 사용하여 회원과 상품이 있는지 확인하고, 있을 경우에 회원과 상품을 findById 하여 리뷰를 작성할때 해당 Idx를 저장하게 구현하였습니다.
- Postman을 통해 API 요청을 보내고 DB에 저장된 모습입니다
2. 이미지 없는 리뷰 조회 기능 구현
2-1. 해당 상품의 리뷰 전체(리스트) 조회
- 해당 상품의 Idx를 통해 상품에 작성된 리뷰를 전체 조회 하는 기능입니다.
- Entity에서 ManyToOne 어노테이션에  FetchType.LAZY 처리를 하여 필요한 속성만 JOIN 되게 처리하였습니다.
- ReviewRepository에서 @Query 를 추가하여 상품 Idx를 조회할 때 불필요한 속성은 조회하지 않게 설정하였습니다.
- 해당 상품에 대해 리뷰 전체가 리스트 형태로 조회된 모습
- FetchType.LAZY 처리하기 전
- FetchType.LAZY 처리한 후
- 이미지가 여러 개 올렸을때 제일 첫 이미지만 보이게 하는 기능을 추후 추가할 예정입니다.
2-2. 해당 리뷰 상세 조회
- 해당 리뷰의 Idx를 통해 리뷰를 상세 조회 하는 기능입니다.
- 전체 조회와 같이 FetchType.LAZY …
> [Feat] 이미지 업로드, 구매 검증 없이 상품 리뷰 작성, 리뷰 조회 기능 구현

- backend/src/main/java/com/synergy/backend/domain/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/CartListReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
#137
cartIdx 리스트로 장바구니 조회, productIdx로 상품 검증
<br><br>
1. cartIdx 리스트로 장바구니를 조회합니다.
기존엔 CustomUserDetails를 통해 유저 idx를 가지고 나의 장바구니 전체 조회만 가능했습니다.
장바구니 조회 비즈니스 로직에 조건문을 추가해서 cartIdx가 들어오면 해당 장바구니 상품만 조회, 없으면 전체조회하도록 했습니다.
```java
if (req.getCartIdxList() == null) {
cartList = cartRepository.findByUserIdx(userIdx);
} else {
cartList = cartRepository.findByUserIdxAndCartIdx(userIdx, req.getCartIdxList());
}
```
2. 기존 상품 검증 코드는 cartIdx를 검증했습니다.
하지만 검증은 상품을 기준으로 발생하기 때문에 productIdx를 받아 해당하는 cartIdx를 리스트로 받고, 반복하여 모두 검증하는 방식으로 변경했습니다.
<br><br>
<br><br>
<br><br>
> [Feat] cartIdx 리스트로 장바구니 조회, productIdx로 상품 검증

- frontend/src/components/order/OrderListComponent.vue
- frontend/src/router/index.js
- frontend/src/stores/useOrderStore.js
#113 
- 주문/배송 목록 조회 기능
<br><br>
- 사이드바 등을 제외하고 주문 배송 목록만 보이는 컴포넌트
- 처음 페이지를 들어가면 전체 주문 목록이 보입니다.
- 년도를 선택하면 해당 년도의 주문 목록만 보이게 됩니다.
- 주문 목록에서 검색어 기능은 없앴습니다.
<br><br>
<br><br>
<br><br>
> [Feat] 주문 배송 목록 ui, axios

- backend/src/main/java/com/synergy/backend/domain/member/model/response/OrderListRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/controller/OrderController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/PresentRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/querydsl/OrderRepositoryCustom.java
- backend/src/main/java/com/synergy/backend/domain/orders/querydsl/OrderRepositoryCustomImpl.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/OrderRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/OrderService.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/PresentService.java
- backend/src/main/java/com/synergy/backend/domain/product/controller/ProductController.java
- backend/src/main/java/com/synergy/backend/domain/product/model/response/SearchProductRes.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
#43 
- 주문 배송 목록 조회 기능
<br><br>
- 파라미터로 year(선택), page, size (필수)를 전달해야합니다.
- year을 같이 보내면 해당 년도의 주문 목록만 조회됩니다.
- 쿼리 dsl 사용 
<br><br>
<br><br>
<br><br>
> [Feat] 주문 배송 목록 조회 기능 구현(#43)

- frontend/src/components/common/HeaderComponent.vue
- frontend/src/components/member/MemberEmailFindModal.vue
- frontend/src/components/member/UpdateMemberInfoComponent.vue
- frontend/src/pages/member/LoginPage.vue
- frontend/src/pages/member/MemberEmailFindPage.vue
- frontend/src/pages/member/MemberInfoPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useMemberStore.js
#154 
- 회원 관련 페이지 구현
- 회원 관련 컴포넌트 분리 및 적용
<br><br>
회원관련 router-link를 정리해놨습니다.
헤더 구현 및 주요기능을 적용하였습니다.
<br><br>
로그아웃 기능 구현 중 발생한 이슈 공유합니다.
기존 -> 로그아웃이 성공시 단순 쿠키만 삭제하고 Handler 처리를 하지 않았을 때
웹브라우저에서 쿠키는 잘 삭제되나, CORS 문제가 발생했습니다.
이후, 로그아웃 성공 시, 핸들러 처리를 해주니 CORS 주소 적용이 아닌, 프록시 적용이 잘 되는것을 확인하였습니다.
구체적인 이유는 모르겠으나, Handler 측에서 req, res 를 인식하여 (Proxy) CORS 문제를 다루는 것이지 않을까 추측해봅니다! 
<br><br>
<br><br>
> [Feat] Member 관련 페이지/컴포넌트 +  Header 컴포넌트 구현 

- frontend/src/components/atelier/AtelierProductListComponent.vue
- frontend/src/components/atelier/AtelierProfileComponent.vue
- frontend/src/components/atelier/AtelierReviewComponent.vue
- frontend/src/pages/atelier/AtelierPage.vue
- frontend/src/router/index.js
#160 
- 작가 프로필 페이지 ui 구현 
<br><br>
- 현재 ui 만 구현해놨습니다 .
- 탭을 누르면 다른 컨텐츠가 나오도록 구현해놨습니다.
- 탭 컨텐츠 중에 작가 프로필과 후기리스트 컴포넌트는 아직 구현 전입니다. 
<br><br>
<br><br>
<br><br>
> 작가 페이지 ui구현 

- frontend/src/components/AdvertiseCarousel.vue
- frontend/src/components/product/CarouselComponent.vue
- frontend/src/components/product/CarouselProductListComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useProductStore.js
#100
페인 페이지 구현
<br><br>
- 메인페이지는 크게 3개의 컴포넌트로 구성됐습니다.
1. 광고 캐러셀 컴포넌트
2. 숏컷 버튼 컴포넌트
3. 상품 캐러셀 컴포넌트
<br><br>
- 아직 캐러셀 디테일 작업이 필요합니다.
<br><br>
<br><br>
> [Feat]메인페이지 구현

- frontend/src/components/mypage/MyFavoriteListComponent.vue
- frontend/src/components/sidebar/MyPageSideBarComponent.vue
- frontend/src/router/index.js
- router 수정
<br><br>
- router-link수정했습니다
<br><br>
<br><br>
<br><br>
> [Fix] 마이페이지 라우터 수정

- frontend/src/App.vue
- frontend/src/components/common/FooterComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/router/index.js
#60
- Footer 컴포넌트 추가
- app.vue에 Header, Footer 컴포넌트 고정
<br><br>
- 푸터컴포넌트 추가
- 헤더컴포넌트, 푸터컴포넌트를 가장 최상단인 App.vue에 넣어놓았습니다.
- index.js에서는 해당 라우터부분을 제거해놓았습니다.
<br><br>
- 이용약관 등을 일단 넣어놓았는데 뺄건지 그대로 놔둘것인지 의논필요
- 하단 내용에는 어떤걸 넣을지 의논필요
<br><br>
> [Feat] Footer 컴포넌트 추가 및 Header, Footer컴포넌트 고정

- backend/src/main/java/com/synergy/backend/domain/grade/model/response/GetMyGradeRes.java
- backend/src/main/java/com/synergy/backend/domain/grade/service/GradeService.java
- backend/src/main/java/com/synergy/backend/domain/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Cart.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/orderMessageReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
#184 
등급 메시지 수정
장바구니 요청 메세지 api 
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 등급 메시지 수정, 장바구니 요청 메세지 api 

- frontend/src/components/order/CartComponent.vue
- frontend/src/stores/useCartStore.js
#184
장바구니 조회 페이지 공방 별 가격
전체 선택상품 수량 
<br><br>
장바구니 조회 페이지 공방 별 가격
전체 선택상품 수량 
기능 수정했고, 요청 메세지는 수정중입니다. !!
<br><br>
<br><br>
<br><br>
> [Feat] 장바구니 조회 페이지 공방 별 가격, 전체 선택상품 수량 

- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/CustomUserDetailService.java
- backend/src/main/java/com/synergy/backend/global/security/filter/LoginFilter.java
- backend/src/main/java/com/synergy/backend/global/security/filter/OAuth2Filter.java
#5 
- 소셜 로그인 성공시, 리다이렉트 주소 변경
- 소셜 로그인 요청 성공시, contextHolder 안에 담기도록 설정
<br><br>
기존, 소셜 로그인이 성공했을 때, 바로 mainPage로 리다이렉트를 시켜놓았던 결과
쿠키 안에 토큰은 원활하게 저장이 되었으나, 클라이언트측에선 유저에 대한 정보를 받을 수 없었던 이슈가 있었습니다.
추가적인 작업을 통해 수정 및 해결 완료 하였습니다.
<br><br>
<br><br>
<br><br>
> [Fix] 소셜 로그인 문제 해결

- backend/build.gradle
- backend/src/main/java/com/synergy/backend/domain/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/CartListReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/orderMessageReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/CartDTO.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/OptionListRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
- backend/src/main/java/com/synergy/backend/global/util/AesUtil.java
- backend/src/main/resources/application.yml
#193
1. 장바구니 추가 api  개선
2. 장바구니 추가 및 암호화 반환 api 
3. 암호화 복호화 및 조회 api 
4. 장바구니 페이지에서 요청 메세지 반환 추가
5. application.yml 에 환경변수 추가(카톡에 남기겠습니다)
<br><br>
**시나리오 구분**
**1. 장바구니**
상세페이지에서 상품을 선택 후 장바구니 추가 api, POST ("/cart")
장바구니로 들어가서 조회 api, GET ("/cart")
**2. 바로 구매하기**
바로 구매하기는 선택한 상품을 장바구니에 추가 후, 해당 선택된 상품을 다시 조회할 수 있게 했습니다.
1. 상품을 선택하고 ("/cart/purchase")를 통해 상품을 저장하고 암호화 코드를 받는다.
2. 상품을 추가하면 cartIdx 리스트가 반환되기 때문에 리스트를 직렬화 한 뒤에 암호화 과정을  거치고 반환해준다.
3. 바로구매하기 페이지에서 해당 암호화 코드를 통해 상품을 조회한다. ("/direct/{encrypt}")
4. 이렇게 하면 바로 구매하기를 눌렀을 때, 방금 선택한 상품만 조회할 수 있으며, 장바구니에 동일한 공방의 동일한 상품이 존재해도 오직 구매하기로 결정한 상품만 조회할 수 있고, 쿼리를 통해 보내주기 때문에 좀 더 효율적인 데이터 처리가 가능함 
**3. 선물하기**
바로 구매하기와 동일
암호화를 통해서 다른 사용자들이 장바구니에 접근할 수 없도록 함
**새로운 상품 추가 api**
```
@PostMapping
public BaseResponse<Void> addCart(@RequestBody …
```
> [Feat] 바로 구매하기, 선물하기를 위한 cartIdx 리스트 암복호화 

- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/CartDTO.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/ProductListRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
#206 
이전 merge에서 누락된 예외처리 코드를 급히 추가했습니다.
겸사겸사 기존에 추가하려고 했던 코드인 장바구니 상품 url을 반환값에 추가하는코드도 추가했습니다.
초기 spring security가 도입되지 않았을 때 배송지 조회 매개변수로 memberIDx를 직접 받았었는데  인증값을 받도록  변경
<br><br>
<br><br>
<br><br>
<br><br>
> [Hotfix] 예외처리 누락 추가 

- backend/src/main/java/com/synergy/backend/domain/product/model/response/ProductInfoRes.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
X
- 단일 상품조회 응답 객체에 공방정보 추가
<br><br>
```
{
"isSuccess": true,
"code": 1000,
"message": "요청에 성공하였습니다.",
"result": {
"productIdx": 1,
"productName": "크루아상",
"productThumbnail": "thumbnail_1.jpg",
"productImages": [
{
"productImageIdx": 1,
"productImageUrl": "image_1.jpg"
},
{
"productImageIdx": 2,
"productImageUrl": "image_2.jpg"
},
{
"productImageIdx": 3,
"productImageUrl": "image_3.jpg"
}
],
"productPrice": 3000,
"productOnSalePercent": 25,
"productOnSalePrice": 750,
"productFinalPrice": 2250,
"productAverageScore": 4.5,
"productOptions": [
{
"name": "크기(사이즈)",
"subOptions": [
{
"name": "S",
"inventory": 50,
"addPrice": 1000
},
{
"name": "M",
"inventory": 40,
"addPrice": 2000
},
{
"name": "L",
"inventory": 30,
"addPrice": 3000
}
]
},
{
"name": "색상",
"subOptions": [
{
"name": "빨강", …
```
> [Add] 단일 상품 정보 응답 객체에 공방 정보 추가 

- backend/src/main/java/com/synergy/backend/domain/atelier/service/AtelierService.java
- backend/src/main/java/com/synergy/backend/domain/likes/controller/LikesController.java
- backend/src/main/java/com/synergy/backend/domain/likes/model/entity/Likes.java
- backend/src/main/java/com/synergy/backend/domain/likes/repository/LikesRepository.java
- backend/src/main/java/com/synergy/backend/domain/likes/service/LikesService.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/Product.java
- backend/src/main/java/com/synergy/backend/domain/product/model/response/ProductListRes.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
#21 #22 #23 
- 찜 기능추가
<br><br>
- 찜한 작품리스트 조회기능을 추가했습니다
- 해당 상품을 찜하면 찜한 작품리스트에 추가됩니다
- 해당 상품을 취소하면 찜한 작품리스트에서 삭제됩니다.
<br><br>
> [Feat] 찜(좋아요) 기능추가

- frontend/src/components/atelier/AtelierProfileCardComponent.vue
- frontend/src/components/common/BottomHeaderComponent.vue
- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/components/common/TopHeaderComponent.vue
- frontend/src/components/member/LoginCallBackComponent.vue
- frontend/src/components/member/UpdateMemberInfoComponent.vue
- frontend/src/components/sidebar/MyPageSideBarComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/member/LoginPage.vue
- frontend/src/router/index.js
X
- 팀원들끼리 회의를 진행하면서 다같이 라우팅 작업
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 팀원간 라우팅 연결 작업

- frontend/src/components/review/ReviewModalComponent.vue
- frontend/src/stores/useReviewCreateStore.js
#197 
- 후기 작성 모달 컴포넌트 및 후기 작성 스토어 추가
<br><br>
- 임의로 해당 버튼을 사용하였습니다.<br>
- 별점이 없고 후기 코멘트가 15자 미만일 경우 '후기 등록하기' 버튼이 활성화되지 않습니다. <br>
- 별점이 있고 후기 코멘트가 15자 이상일 경우 '후기 등록하기' 버튼이 활성화됩니다.
<br><br>
> [Feat] 후기 작성 모달 컴포넌트 및 후기 작성 스토어 추가

- backend/src/main/java/com/synergy/backend/domain/hashtag/model/entity/Hashtag.java
- backend/src/main/java/com/synergy/backend/domain/hashtag/model/entity/ProductHashtag.java
- backend/src/main/java/com/synergy/backend/domain/hashtag/repository/HashTagRepository.java
- backend/src/main/java/com/synergy/backend/domain/hashtag/repository/ProductHashTagRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Orders.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Present.java
- backend/src/main/java/com/synergy/backend/global/DataInit.java
#해당없음
initData 추가
<br><br>
- member
3명의 회원
각 이메일은 member1@email.com, member2@email.com, member3@email.com 
비밀번호는 qwer1234를 암호화한 값으로 넣어놨습니다.
- category
- atelier
- hashtag
- product
- product-hashtag
- present
- orders
---
@PostConstruct 
해당 어노테이션이 주석처리되면 데이터가 생성되지 않습니다.
<br><br>
<br><br>
<br><br>
> backend initData 추가

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/CountDown.vue
- frontend/src/components/product/CarouselComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/atelier/AtelierPage.vue
- frontend/src/stores/useProductStore.js
#num
- 메인 페이지 상품 캐러셀 작업
<br><br>
- 무한 넘김 가능하도록 변경
- "추석" 해시태그 상품 캐러셀과 , "오늘의 핫딜" 해시태그 상품 캐러셀 구현
- 오늘의 핫딜에 카운트 다운 추가
<br><br>
- 아직 더보기 연결 x
<br><br>
<br><br>
> [Feat]메인페이지 상품 캐러셀 디테일 

- backend/src/main/java/com/synergy/backend/domain/orders/model/response/AtelierListRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/CartProductListRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
X
productListRes -> CartProductListRes 네이밍 변경
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] dto 클래스 네이밍 수정 

- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
<br><br>
<br><br>
<br><br>
<br><br>
> [Deploy] 배포 테스트 02

- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> 0533 테스트 03

- frontend/src/App.vue
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Test] jenkins 테스트 5

- frontend/src/App.vue
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Deploy] 배포 테스트 09

- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Deploy] 배포 테스트 06

- frontend/src/App.vue
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Test] jenkins 테스트 07

- backend/src/main/java/com/synergy/backend/domain/product/model/entity/ProductImages.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/ProductMajorOptions.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/ProductSubOptions.java
- backend/src/main/java/com/synergy/backend/domain/product/repository/ProductImagesRepository.java
- backend/src/main/java/com/synergy/backend/global/DataInit.java
#해당없음
- 상품 관련 데이터 넣는 코드 추가 
<br><br>
- 상품 이미지 테이블에 s3 이미지 url 추가
- major 옵션, sub 옵션 추가
<br><br>
<br><br>
<br><br>
> [Feat] 상품 관련 데이터 init 코드 추가

- document/05_ERD/README.md
- X
- ERD를 수정된 DB에 맞게 수정
<br><br>
- 'come'공방 v1.1' 로 하여 DB에 맞게 테이블, 칼럼, 연관 관계 등을 수정하였습니다. <br>
- 시크릿 모드로 접속하여 수정 할 수 없는걸 확인하였습니다.
<br>
> [Docs] ERD 수정

- backend/src/main/java/com/synergy/backend/domain/follow/service/FollowService.java
- backend/src/main/java/com/synergy/backend/domain/grade/service/GradeService.java
- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberEmailAuthController.java
- backend/src/main/java/com/synergy/backend/domain/member/model/response/MemberInfoRes.java
- backend/src/main/java/com/synergy/backend/domain/member/service/MemberService.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
- backend/src/main/java/com/synergy/backend/domain/review/service/ReviewService.java
- backend/src/main/java/com/synergy/backend/global/DataInit.java
- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
X
- 회원 관련 예외처리 추가 (중복 이메일 검증)
- 기존 회원 예외 메시지 수정
- 로그인 성공시, 초기값에 줄 정보로 등급정보 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] 회원 관련 예외처리 추가 + 로그인 성공 시 응답 정보 추가

- backend/src/main/java/com/synergy/backend/domain/grade/model/entity/Grade.java
- backend/src/main/java/com/synergy/backend/domain/member/model/entity/Member.java
- backend/src/main/java/com/synergy/backend/domain/member/model/request/MemberSignupReq.java
- backend/src/main/java/com/synergy/backend/domain/member/model/response/MemberInfoRes.java
- backend/src/main/java/com/synergy/backend/domain/member/service/MemberService.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/Product.java
- backend/src/main/java/com/synergy/backend/global/DataInit.java
- backend/src/main/java/com/synergy/backend/global/security/filter/OAuth2Filter.java
X
- 로그인시, 장바구니에 담은 정보도 전달
- 상품 생성시, 평점 0.0 으로 생성
- 회원 가입시, 가장 낮은 등급 배정
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] 회원 관련 반환 정보 추가 + 상품, 회원 버그 수정

- frontend/src/components/common/FooterComponent.vue
- frontend/src/components/product/CarouselProductDetailComponent.vue
- frontend/src/pages/mypage/MyPage.vue
- frontend/src/pages/product/ProductDetailPage.vue
- 상세상품페이지에 이미지캐러셀추가
<br><br>
- 라이브러리 말고 이미지 클릭시 사진이 크게 보이게 했습니당
<br><br>
<br><br>
> [Feat] 상세상품페이지에 이미지 캐러셀 추가

- frontend/src/components/AskCommentComponent.vue
- frontend/src/components/common/TopHeaderComponent.vue
- frontend/src/pages/product/ProductDetailPage.vue
- 비밀댓글
- 탑헤더 알림안나오게 수정
- 작품정보 다 나오게 수정
<br><br>
헤더수정
작품정보수정
비밀댓글수정ing
<br><br>
- 비밀댓글은 아직 수정중입니다. 데이터에 0으로만 저장이 되어서 무엇이 문제인지 파악중입니다.
<br><br>
> [Feat] 헤더, 작품정보,비밀댓글 수정

- backend/src/main/java/com/synergy/backend/domain/product/controller/ProductController.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
#해당없음
customuserdetail 이 null 일 때 나는 에러 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] customuserdetail null처리 관련 에러 수정

- backend/src/main/java/com/synergy/backend/domain/product/controller/ProductController.java
- backend/src/main/java/com/synergy/backend/domain/product/querydsl/ProductRepositoryCustom.java
- backend/src/main/java/com/synergy/backend/domain/product/querydsl/ProductRepositoryCustomImpl.java
- backend/src/main/java/com/synergy/backend/domain/product/repository/CategoryRepository.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
- backend/src/main/java/com/synergy/backend/global/DataInit.java
#47 
- 키워드로 검색 기능 개발
<br><br>
해당 요소에 키워드가 포함돼있는 상품 리스트
- 공방의 이름, title
- 상품의 이름
- 카테고리의 이름 +관련되 하위 카테고리 상품
- 해시태그 이름
<br><br>
카테고리와 관련된 상품 검색 시에 하위 카테고리를 찾을 때  jpa를 이용해 구현했는데, 자기 참조 테이블에 유용한 recursive CTE가 있다고 해서 사용해봄. native 쿼리를 사용해야하는데, 뭐가 더 나은지 좀더 고민이 필요하며, 더 많은 성능 개선이 필요함.
어떤 부분에서는 검색이 잘 되는데, '뷁'이란 단어에도 왜 검색 결과가 나오는지 모르겠음
검색 정확성을 높일 필요성이 있음
<br><br>
<br><br>
> [Feat] 상품 키워드 검색 기능

- backend/src/main/java/com/synergy/backend/domain/product/model/response/ProductMajorOptionsRes.java
- backend/src/main/java/com/synergy/backend/domain/product/model/response/ProductSubOptionsRes.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
#252 
- 상품 상세페이지 수정
<br><br>
- 옵션과 서브 옵션 res 반환에 idx 넣어서 반환해주도록 수정
<br><br>
<br><br>
<br><br>
> [Feat] 상품 상세 페이지 수정

- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/stores/useCartStore.js
#141 
- 상품 상세 페이지 버튼 연결 (장바구니, 결제하기)
- 상품 상세 페이지 옵션 개선
<br><br>
- 상품 상세페이지에서 장바구니 누르면 장바구니로 이동합니다.
- 구매하기 버튼을 누르면 바로 구매 장바구니 페이지로 이동합니다.
- 옵션을 선택하지 않으면 페이지 이동하지 않습니다.
<br><br>
1. 장바구니에 다른 옵션을 선택해도 수량만 증가합니다.
2. 구매하기 눌렀을 경우 암호화값을 받은 후에 , Index.js 설정된 경로대로 `cart/direct/${암호화}` 해서 보냈는데, 같은 옵션의 경우 수량이 늘어나야 하는데 옵션이 추가됩니다.
<br><br>
<br><br>
> [Feat]상품 상세 페이지 결제 컴포넌트 부분 개선

- backend/src/main/java/com/synergy/backend/domain/atelier/repository/AtelierRepository.java
- backend/src/main/java/com/synergy/backend/domain/atelier/service/AtelierService.java
- backend/src/main/java/com/synergy/backend/domain/likes/model/response/LikesInfoResponse.java
- backend/src/main/java/com/synergy/backend/domain/likes/repository/LikesRepository.java
- backend/src/main/java/com/synergy/backend/domain/likes/service/LikesService.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/Product.java
- backend/src/main/java/com/synergy/backend/domain/product/model/response/ProductInfoRes.java
- backend/src/main/java/com/synergy/backend/domain/product/model/response/ProductListRes.java
- backend/src/main/java/com/synergy/backend/domain/product/repository/ProductRepository.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
- backend/src/main/java/com/synergy/backend/global/DataInit.java
#22 
- 상품 목록 중, 좋아요 기능 추가 (성능 low) (X)
- 상품 목록 중, 좋아요 기능 추가 (성능 high)
- 네이밍 컨벤션 적용
- JPQL 에 따른 좋아요 카운트 수 형 변환 (int -> Long)
<br><br>
기능은 동작하나 N+1 을 해결하지 못한, 좋지못한 성능의 코드입니다! 
JPQL 을 활용하여 성능을 높일 예정입니다.
------------------------------
<적용완료> 
JPQL 을 적용하여, 조회 성능을 높였습니다. 
-> 상품의 수만큼 SELECT 문이 발생하던 문제를 2번의 쿼리로 개선하였습니다.
<br><br>
- @OneToMany 를 사용하지 않음으로서, One 측에서 Many 를 참조할 수 없어서 JPQL 에게 특정 DTO 를 적용시켜야만하는 상황이 발생하였습니다. 추후 해당 부분에 대해서 @OneToMany 적용여부를 고려하겠습니다.
<br><br>
<br><br>
> [Feat] 공방 상품에 대한 좋아요 여부 조회 기능 구현 

- backend/src/main/java/com/synergy/backend/domain/likes/model/response/LikesInfoResponse.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
- merge 과정 중 생긴 에러 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Hotfix] Response 객체 인식 수정

- frontend/src/components/mypage/BaseTabComponent.vue
- frontend/src/components/mypage/FollowAtelierListComponent.vue
- frontend/src/components/mypage/MyFavoriteListComponent.vue
- frontend/src/pages/product/ProductListPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useFollowStore.js
#num
- 탭컴포넌트화 
- 팔로우하는작가 
<br><br>
- 마이페이지의 탭을 컴포넌트화했습니다.
- 탭을 사용할때 BaseTabComponent를 가져다 쓰면 됩니다!
<br><br>
<br><br>
> [Feat] 팔로우하는 작가

- backend/build.gradle
- backend/src/main/java/com/synergy/backend/domain/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/AddCartReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
- backend/src/main/java/com/synergy/backend/domain/review/repository/ReviewRepository.java
- backend/src/main/java/com/synergy/backend/global/InitData/DataInit.java
- backend/src/main/java/com/synergy/backend/global/InitData/InitDataWith300000.java
- backend/src/main/resources/application.yml
#242 
#258 
장바구니 기능, actuator, prometheus
<br><br>
1. 장바구니 저장
2. 바로구매하기
3. actuator, prometheus 추가했습니다. 
4. 회원 수 30만명 추가하는 dataInit 만들고 @PostConstruct는 주석해놨습니다. 
<br><br>
30 분 스케줄러로 (cartType.Direct_Purchase) 인 상품중 구매하지 않은 상품은 (cartType.Default)로 변경해서
장바구니에 저장되도록 하는 것
<br><br>
<br><br>
> [Feat] actuator, prometheus , 장바구니 개선 

- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/filter/JwtFilter.java
- backend/src/main/java/com/synergy/backend/global/security/filter/LoginFilter.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/model/RefreshToken.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/repository/RefreshTokenRepository.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/service/RefreshTokenService.java
- backend/src/main/java/com/synergy/backend/global/util/JwtUtil.java
AccessToken 2시간 설정
RefreshToken 일주일  설정
<br><br>
Refresh Token을 구현하여, 만료가되었을 시 오류가 없도록 하였습니다.
<br><br>
<br><br>
<br><br>
> [Feat] Refresh Token 구현

- frontend/src/components/order/CartComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/stores/useCartStore.js
#267 
1. 상세페이지 -> 장바구니, 바로구매하기에서 개선
2. watch 로 페이지 리로딩
<br><br>
1. 상세페이지 -> 장바구니, 바로구매하기에서 개선
prop로 페이지 type을 가져오는데 if문 바깥에 fetchCartlist()가 존재해서 type에 상관없이 장바구니를 호출
그래서 바로구매하기에서도 장바구니가 떴던 문제 해결
2. watch 로 페이지 리로딩
장바구니 <-> 바로 구매하기 페이지 이동 시 페이지 리로딩 하도록
3. 상세페이지에서 장바구니 담기 시 productIdx 보내주도록 
<br><br>
<br><br>
<br><br>
> [Feat] 장바구니 개선 

- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/components/product/ProductList4LayoutComponent.vue
- frontend/src/components/product/ProductList5LayoutComponent.vue
- frontend/src/pages/product/CategoryProductListPage.vue
- frontend/src/pages/product/ProductListPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useLikesStore.js
- frontend/src/stores/useProductStore.js
#260 
로그인 안한 사용자 예외처리
<br><br>
- 기존 코드는 로그인 안한 사용자가 좋아요 누르면 하트 색은 바뀌고 요청은 실패.
- 요청을 받아서 error가 나면 false 반환
- false받으면 하트 색 안바뀌고 알람만 뜨게
<br><br>
<br><br>
<br><br>
> [Fix]좋아요 기능 예외처리(#260)

- frontend/src/pages/MainPage.vue
- frontend/src/pages/product/HashTagProductListPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useProductStore.js
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 상품 캐러셀 더보기 연결

- backend/src/main/java/com/synergy/backend/domain/likes/controller/LikesController.java
- backend/src/main/java/com/synergy/backend/global/InitData/DataInit.java
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix]좋아요 기능 예외처리

- frontend/src/components/common/TopHeaderComponent.vue
- frontend/src/stores/useAtelierStore.js
- frontend/src/stores/useMemberStore.js
- 주석 및 alert 제거
- 
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] 프론트 전체 기능 점검 및 수정

- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/filter/OAuth2Filter.java
- 소셜 로그인 시에도 Refresh 토큰 도입
- 쿠키를 지우고 로그아웃 요청을 보내면 null 로 인한 에러 해결
- 로그아웃시 JSSESSION 삭제
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor,Fix] 소셜 Refresh Token 추가, 쿠키 없을 때 로그아웃 요청 에러 해결

- frontend/src/components/atelier/AtelierProductListComponent.vue
- frontend/src/components/atelier/AtelierProfileCardComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/pages/atelier/AtelierPage.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/router/index.js
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat]공방 페이지 라우팅 처리

- frontend/src/components/AskCommentComponent.vue
- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/components/product/CarouselProductDetailComponent.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useAskCommentStore.js
#num
- 상세페이지
- 사진캐러셀 수정완료
- 문의댓글 수정완료
- 공방컴포넌트 
- 미들헤더 수정
<br><br>
- 상세페이지에서 문의댓글, 사진캐러셀 수정완료
- 미들헤더 관심, 내정보 클릭시 로그인안되어있으면 이동안되도록 수정완료
- 공방컴포넌트는 해당 idx로 이동하게 수정
<br><br>
<br><br>
> [Feat] 상세페이지 사진캐러셀, 문의댓글, 공방컴포넌트 수정

- backend/src/main/java/com/synergy/backend/domain/atelier/model/entity/Atelier.java
- backend/src/main/java/com/synergy/backend/domain/atelier/repository/AtelierProfileImagesRepository.java
- backend/src/main/java/com/synergy/backend/domain/follow/controller/FollowController.java
- backend/src/main/java/com/synergy/backend/domain/follow/model/response/FollowAtelierResponse.java
- backend/src/main/java/com/synergy/backend/domain/follow/repository/FollowRepository.java
- backend/src/main/java/com/synergy/backend/domain/follow/service/FollowService.java
- backend/src/main/java/com/synergy/backend/domain/likes/controller/LikesController.java
- backend/src/main/java/com/synergy/backend/domain/likes/repository/LikesRepository.java
- backend/src/main/java/com/synergy/backend/domain/likes/service/LikesService.java
- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/filter/OAuth2Filter.java
#num
- 팔로우 작가 기능 개발
<br><br>
<br><br>
의논이 필요하여 사진 제외 기본정보만 제공하였습니다! 
<br><br>
<br><br>
> [Feat] 팔로우 하는 작가목록 기능 개발

- backend/src/main/java/com/synergy/backend/domain/atelier/repository/AtelierProfileImagesRepository.java
- backend/src/main/java/com/synergy/backend/domain/follow/service/FollowService.java
- 공방 이미지들 정보 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 공방 팔로우 응답 안에 공방 이미지들 정보 추가

- frontend/src/components/coupon/CouponComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/router/index.js
- frontend/src/stores/useCartStore.js
#267 
장바구니에 연결되지 않은 링크를 연결하고
(작가페이지 링크)
할인율을 적용했습니다.
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 장바구니에 연결되지 않은 링크, 할인율 연결

- backend/src/main/java/com/synergy/backend/domain/ask/controller/AskController.java
- backend/src/main/java/com/synergy/backend/domain/ask/model/request/AskReq.java
- backend/src/main/java/com/synergy/backend/domain/ask/service/AskService.java
- backend/src/main/java/com/synergy/backend/global/InitData/DataInit.java
- 비밀댓글 수정
<br><br>
- store까지 값이 너무 잘 들어가는데 백에는 안들어가져서 왜그런지 엄청 찾았는데 AskReq에서 타입이 boolean이 아니라 Boolean이어야 @Requestbody가 바인딩을 시켜줘서 그부분을 수정해서 pr 날렸습니당~~~~~~ 트러블슈팅에 올려놓았음!
<br><br>
<br><br>
> [Fix] 문의 비밀댓글 Boolean타입으로 수정

- frontend/src/components/common/EmptyContentComponent.vue
- frontend/src/components/order/OrderListComponent.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/stores/useOrderStore.js
#해당없음
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 디테일 개선

- frontend/src/components/common/HeaderCategoriesComponent.vue
- frontend/src/components/product/ProductComponent.vue
- frontend/src/components/product/ProductDetailLeftComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/product/CategoryProductListPage.vue
- frontend/src/pages/product/HashTagProductListPage.vue
- frontend/src/stores/useProductStore.js
#해당없음
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 상품 리스트 디테일 수정

- backend/src/main/java/com/synergy/backend/domain/product/controller/ProductController.java
- backend/src/main/java/com/synergy/backend/domain/product/model/request/CategoryProductListReq.java
- backend/src/main/java/com/synergy/backend/domain/product/querydsl/ProductRepositoryCustom.java
- backend/src/main/java/com/synergy/backend/domain/product/querydsl/ProductRepositoryCustomImpl.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
#해당없음
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix]상품 리스트 필터링 추가 및 디테일 수정

- frontend/src/pages/product/ProductDetailPage.vue
#해당없음
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
#288 수정사항에서 난 productDetailPage 머지 에러 #276 의 productDetailPage로 수정
<br><br>
<br><br>
<br><br>
> [Fix] 상품 디테일 페이지 머지 에러 해결

- backend/src/main/java/com/synergy/backend/domain/coupon/controller/CouponController.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/entity/Coupon.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/type/CouponType.java
- backend/src/main/java/com/synergy/backend/domain/coupon/repository/CouponRepository.java
- backend/src/main/java/com/synergy/backend/domain/coupon/scheduler/CouponScheduler.java
- backend/src/main/java/com/synergy/backend/domain/coupon/service/CouponService.java
- backend/src/main/java/com/synergy/backend/domain/grade/model/entity/Grade.java
- backend/src/main/java/com/synergy/backend/domain/grade/model/response/GetMyGradeRes.java
- backend/src/main/java/com/synergy/backend/domain/grade/scheduler/GradeScheduler.java
- backend/src/main/java/com/synergy/backend/domain/grade/service/GradeService.java
- backend/src/main/java/com/synergy/backend/domain/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/OrderRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/Product.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/ProductMajorOptions.java
- backend/src/main/java/com/synergy/backend/global/InitData/InitDataWith300000.java
- backend/src/main/java/com/synergy/backend/global/InitData/user1000.java
- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
#295 
등급, 쿠폰에 대한 로그를 영어에서 한글로 변경 (가독성 향상을 위해)
장바구니 조회 수정
<br><br>
1. 등급 쿠폰에 대한 로그를 변경했고, 
```
log.info("Upgrading member {} from grade {} to grade {}.", member.getIdx(), curGradeIdx, expectedGradeIdx);
log.info("회원 {}: 기존 등급 {} → 변경 등급 {}", member.getIdx(), curGradeIdx, expectedGradeIdx);
```
2. 장바구니 특정 리스트 조회 로직을 수정했습니다. 
<br><br>
<br><br>
<br><br>
> [Feat] 등급, 쿠폰 스케줄러 로그 추가 , cart getCart 로직 수정 

- frontend/src/components/member/DeliveryComponent.vue
- frontend/src/components/mypage/GradeComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/router/index.js
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useDeliveryStore.js
- frontend/src/stores/useReviewStore.js
#294
스크롤
withCredentials: true 가 빠져있던 곳 추가 
<br><br>
index.js 
아래 코드 추가해서 스크롤 기억하도록 했습니다. 
```
scrollBehavior(to, from, savedPosition) {
if (to.hash) {
return {
el: to.hash,
behavior: 'smooth',
};
} else if (savedPosition) {
return savedPosition;
} else {
return { top: 0 };
}
},
```
<br><br>
<br><br>
<br><br>
> [Feat] 자동 스크롤 구현, css 정리 

- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/filter/JwtFilter.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/model/BlackListToken.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/repository/BlackListTokenRepository.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/service/BlackListTokenService.java
#297 
- 매 요청 때마다 블랙리스트 여부 판단 ( 성능 low )
- 로그아웃 요청 시, 블랙리스트 명단에 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] refresh token 전략으로 블랙리스트 추가

- backend/src/main/java/com/synergy/backend/domain/coupon/repository/MemberCouponRepository.java
- backend/src/main/java/com/synergy/backend/domain/coupon/service/CouponService.java
- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
#300 
이벤트 쿠폰 중복 수급 방지 기능 
커밋 메세지 실수로 잘못 올렸습니다..
<br><br>
memberCoupon 테이블을 조회해서 동일 이벤트 쿠폰을 중복으로 받지 못하게 했습니다. 
<br><br>
<br><br>
<br><br>
> [Feat] 이벤트 쿠폰 개선

- frontend/src/components/member/DeliveryComponent.vue
x
배송지 없을 때 페이지
<br><br>
배송지 없을 때 페이지
<br><br>
<br><br>
<br><br>
> [Feat] 배송지 없을 때 페이지

- backend/src/main/java/com/synergy/backend/domain/orders/controller/OrderController.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/OptionInCartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/OrderService.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/ProductSubOptions.java
- backend/src/main/java/com/synergy/backend/domain/product/repository/ProductSubOptionsRepository.java
- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
- backend/src/main/java/com/synergy/backend/global/config/impConfig.java
#num
- 결제 코드 진행중
<br><br>
- 카트 테이블에서 삭제하는 코드가 잘 안돼서 일단 주석
<br><br>
<br><br>
<br><br>
> [Fix] 결제 코드 진행중

- backend/src/main/java/com/synergy/backend/domain/product/controller/ProductController.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/Product.java
- backend/src/main/java/com/synergy/backend/domain/product/model/response/ProductInfoRes.java
- backend/src/main/java/com/synergy/backend/domain/product/querydsl/ProductRepositoryCustom.java
- backend/src/main/java/com/synergy/backend/domain/product/querydsl/ProductRepositoryCustomImpl.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
- 단일 상품 회원 좋아요 여부 추가
- 해시태그 상품 좋아요 여부 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [Add] 단일 상품, 해시태그 상품 조회 회원 좋아요 여부 추가

- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useMemberStore.js
- 장바구니 물품 수에 따라서 상품수 표시
<br><br>
비로그인 일 때 
-> 표시 x 
로그인 일 때 
-> 0개 혹은 개수로 표시
장바구니 담기 / 삭제 
-> 요청에 따른 개수 변경
<br><br>
<br><br>
<br><br>
> [Add] 장바구니 물품 개수만큼 상단 헤더에 표시

- backend/src/main/java/com/synergy/backend/domain/member/service/MemberService.java
<br><br>
<br><br>
<br><br>
<br><br>
> [Add] 장바구니 담은 상품 개수 반환

- frontend/src/components/atelier/AtelierProfileCardComponent.vue
- frontend/src/components/gift/GiftGiveListComponent.vue
- frontend/src/components/gift/GiftReceivedListComponent.vue
- frontend/src/components/mypage/FollowAtelierListComponent.vue
- frontend/src/components/mypage/MyFavoriteListComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/components/product/ProductList4LayoutComponent.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useAtelierStore.js
- frontend/src/stores/useLikesStore.js
- 상세페이지 공방 관련 실시간 변동으로 수정
- 공방페이지 관련 찜 여부 실시간 변동으로 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 팔로우 / 좋아요 관련 오류 수정 및 실시간 변동 추적

- backend/src/main/java/com/synergy/backend/domain/coupon/controller/CouponController.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/entity/Coupon.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/entity/MemberCoupon.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/request/CouponListRes.java
- backend/src/main/java/com/synergy/backend/domain/coupon/repository/MemberCouponRepository.java
- backend/src/main/java/com/synergy/backend/domain/coupon/service/CouponService.java
#45 
내 쿠폰 목록 조회
<br><br>
내 쿠폰 목록을 조회합니다.
쿠폰의 종류가 많지 않기 때문에 페이징 처리를 하지는 않았습니다.
coupon 엔티티에서 쿠폰 사용기간을 LocalDateTime 타입에서 에서 Duration  타입으로 변경했습니다. 
<br><br>
<br><br>
<br><br>
> [Feat] 내 쿠폰 목록 조회

- backend/src/main/java/com/synergy/backend/domain/review/controller/ReviewController.java
- backend/src/main/java/com/synergy/backend/domain/review/model/response/WritableReviewRes.java
- backend/src/main/java/com/synergy/backend/domain/review/repository/ReviewRepository.java
- backend/src/main/java/com/synergy/backend/domain/review/service/ReviewService.java
#314 
- 작성 가능한 후기 목록
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 작성 가능한 후기 목록

- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/components/review/ReviewOfPurposeComponent.vue
- frontend/src/components/review/WritableReviewComponent.vue
- frontend/src/components/sidebar/MyPageSideBarComponent.vue
- frontend/src/pages/product/HashTagProductListPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useReviewStore.js
#312 
- 작성 가능한 후기 목록
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 작성 가능한 후기 목록 컴포넌트

- frontend/src/components/mypage/FollowAtelierListComponent.vue
- frontend/src/components/mypage/MyFavoriteListComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/components/product/ProductList5LayoutComponent.vue
- frontend/src/stores/useFollowStore.js
- 메인페이지 에서도 좋아요 실시간 변동 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 5 Layout 좋아요 실시간 변동 수정

- frontend/src/components/AskCommentComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useGiftStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useOrderStore.js
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 기본 기능 테스트중 수정

- backend/src/main/java/com/synergy/backend/domain/ask/controller/AskController.java
- backend/src/main/java/com/synergy/backend/domain/ask/service/AskService.java
- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
- backend/src/main/java/com/synergy/backend/domain/member/model/request/IsMemberReq.java
- backend/src/main/java/com/synergy/backend/domain/member/service/MemberService.java
- backend/src/main/java/com/synergy/backend/domain/orders/controller/CartController.java
- backend/src/main/java/com/synergy/backend/domain/orders/controller/OrderController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/OrderConfirmReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/request/OrderPresentReq.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/OrderService.java
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 기능 테스트 중 수정

- backend/src/main/java/com/synergy/backend/domain/coupon/controller/CouponController.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/response/EventCouponListRes.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/response/MyCouponListRes.java
- backend/src/main/java/com/synergy/backend/domain/coupon/model/type/IssueDate.java
- backend/src/main/java/com/synergy/backend/domain/coupon/repository/CouponRepository.java
- backend/src/main/java/com/synergy/backend/domain/coupon/service/CouponService.java
#325 
이벤트 쿠폰 목록 조회 기능
<br><br>
발급 가능한 날짜의 이벤트 쿠폰 조회 기능입니다.
발급 가능한 수량은 계산하지 않았습니다. 
<br><br>
<br><br>
<br><br>
> [Feat] 이벤트 쿠폰 목록 조회 기능 

- frontend/src/components/member/UpdateMemberInfoComponent.vue
- 버튼 색상 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Design] 버튼 색상 변경

- frontend/src/components/common/HeaderCategoriesComponent.vue
- frontend/src/components/mypage/FollowAtelierListComponent.vue
- 팔로우하는작가 썸네일 css수정
<br><br>
<br><br>
<br><br>
> [Design] 팔로우하는 작가 썸네일 css수정

- frontend/src/components/AskCommentComponent.vue
- frontend/src/components/common/HeaderCategoriesComponent.vue
- frontend/src/components/gift/GiftGiveListComponent.vue
- frontend/src/components/mypage/BaseTabComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/components/product/CarouselProductDetailComponent.vue
- frontend/src/components/product/ProductComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/components/product/ProductList5LayoutComponent.vue
- frontend/src/components/review/ReviewModalComponent.vue
- frontend/src/components/review/ReviewOfPurposeComponent.vue
- frontend/src/components/sidebar/MyPageSideBarComponent.vue
- frontend/src/pages/member/LoginPage.vue
- frontend/src/pages/member/SignupPage.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/stores/useAskCommentStore.js
- frontend/src/stores/useAtelierStore.js
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useDeliveryStore.js
- frontend/src/stores/useGradeStore.js
- frontend/src/stores/useLikesStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useOrderStore.js
- frontend/src/stores/useProductStore.js
- frontend/src/stores/useReviewStore.js
#해당없음
- 기본 기능 디테일 수정
<br><br>
- 상품 상세페이지 이미지 캐러셀 수정
<br><br>
<br><br>
<br><br>
> [Fix] 디테일 수정

- backend/src/main/java/com/synergy/backend/domain/follow/model/entity/Follow.java
- backend/src/main/java/com/synergy/backend/domain/likes/model/entity/Likes.java
- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
- backend/src/main/java/com/synergy/backend/domain/member/model/entity/Member.java
- backend/src/main/java/com/synergy/backend/domain/member/service/MemberService.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Cart.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/OptionInCart.java
- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
#7 
- 회원탈퇴 기능 개발
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 회원탈퇴 api 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/AskCommentComponent.vue
- frontend/src/components/common/BottomHeaderComponent.vue
- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/components/common/TopHeaderComponent.vue
- frontend/src/components/gift/GiftReceivedDetailComponent.vue
- frontend/src/components/member/UpdateMemberInfoComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/components/product/ProductList4LayoutComponent.vue
- frontend/src/components/product/ProductList5LayoutComponent.vue
- frontend/src/components/review/ProductReviewListComponent.vue
- frontend/src/components/review/ReviewModalComponent.vue
- frontend/src/main.js
- frontend/src/pages/member/LoginPage.vue
- frontend/src/pages/member/SignupPage.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useDeliveryStore.js
- frontend/src/stores/useLikesStore.js
- frontend/src/stores/useOrderStore.js
- sweetalert 적용
<br><br>
- sweetalert 적용
- npm i vue-sweetalert2  설치하기
<br><br>
- 적용했을때 에러가 나는 부분이 있어서 TODO로 적어놓았습니당
<br><br>
> [feat] sweetalert 적용

- frontend/src/components/member/LoginCallBackComponent.vue
- frontend/src/components/member/MemberEmailFindModal.vue
- frontend/src/components/member/UpdateMemberInfoComponent.vue
- frontend/src/pages/member/MemberEmailFindPage.vue
- frontend/src/stores/useMemberStore.js
- 소셜 로그인 시도시, 로그인 처리 되던 오류 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix, Feat] 소셜 로그인처리 에러 수정 + 회원 탈퇴 버튼 및 모달 구현

- backend/src/main/java/com/synergy/backend/global/common/BaseResponseStatus.java
- backend/src/main/java/com/synergy/backend/global/exception/GlobalExceptionHandler.java
- backend/src/main/resources/application.yml
#337 
예외처리 추가 
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 예외처리 추가 

- frontend/src/api/response.js
- frontend/src/components/coupon/eventCouponComponent.vue
- frontend/src/components/error/ErrorComponent.vue
- frontend/src/components/error/NotFoundComponent.vue
- frontend/src/main.js
- frontend/src/router/index.js
#338 
예외페이지 생성
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 예외 페이지 생성

- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/pages/product/CategoryProductListPage.vue
- frontend/src/stores/useOrderStore.js
- frontend/src/stores/useProductStore.js
#46 #36 
- 상품 카테고리 검색 오류 수정
- 결제 오류 수정
<br><br>
- 상품 카테고리 검색하면 모든 상품이 검색되는 오류 수정
- 결제 페이지에서 결제하기 누르면 다른 페이지로 이동해버리는 에러 수정
<br><br>
- 아마 해시태그 검색도 같은 에러가 있을 것으로 예상. 추후 수정 예정
<br><br>
<br><br>
> [Fix] 상품 카테고리 검색 에러, 결제 에러 수정

- backend/src/main/java/com/synergy/backend/global/exception/GlobalExceptionHandler.java
- backend/src/main/resources/application.yml
#337
글로벌 예외처리기 500제거  
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 글로벌 예외처리기 500제거  

- frontend/src/api/response.js
- frontend/src/components/error/ErrorComponent.vue
#338 
if else 문에서 else 제거 
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 프론트 404 예외처리 변경 

- frontend/src/components/AskCommentComponent.vue
- frontend/src/components/common/BottomHeaderComponent.vue
- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/components/common/TopHeaderComponent.vue
- frontend/src/components/gift/GiftReceivedDetailComponent.vue
- frontend/src/components/member/UpdateMemberInfoComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/components/product/ProductList4LayoutComponent.vue
- frontend/src/components/product/ProductList5LayoutComponent.vue
- frontend/src/components/review/ProductReviewListComponent.vue
- frontend/src/components/review/ReviewModalComponent.vue
- frontend/src/pages/member/LoginPage.vue
- frontend/src/pages/member/SignupPage.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/stores/useAtelierStore.js
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useDeliveryStore.js
- frontend/src/stores/useLikesStore.js
- frontend/src/stores/useOrderStore.js
- 긴급수정
<br><br>
<br><br>
<br><br>
<br><br>
> [HotFix] 라이브러리 도입 오류 수정

- backend/src/main/java/com/synergy/backend/domain/follow/controller/FollowController.java
- 팔로우 예외처리 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 비로그인 회원 팔로우 시도 예외처리 추가

- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/filter/OAuth2AuthenticationFailureHandler.java
- 실패 로그 수집을 위한 failure handler구현
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] Oauth2 failure 핸들러 구현

- frontend/src/components/coupon/eventCouponComponent.vue
- 이벤트 쿠폰에서 모달창 alert라이브러리로 변경
<br><br>
<br><br>
> [Fix] 모달창 alert로 변경하기

- frontend/src/components/mypage/BaseTabComponent.vue
- frontend/src/components/mypage/FollowAtelierListComponent.vue
- frontend/src/components/mypage/MyFavoriteListComponent.vue
- frontend/src/components/sidebar/MyPageSideBarComponent.vue
- 최근본상품삭제
- 팔로우하는 작가 버튼 수정
<br><br>
<br><br>
> [Fix] 팔로우하는 작가 수정 및 최근본상품삭제

- frontend/src/components/mypage/FollowAtelierListComponent.vue
- frontend/src/components/order/OrderListComponent.vue
- 팔로우하는 작가 router-link수정
- 주문배송내역 margin-top 삭제
> [Fix] 팔로우하는 작가 router-link 수정 및 주문배송내역 css수정

- frontend/src/components/common/HeaderCategoriesComponent.vue
- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/stores/useCategoryStore.js
- 카테고리 최초 한 번 클릭시에만, 요청 할 수 있도록 성능개선
<br><br>
로컬 스토리지에 저장함으로서, 조회 및 렌더링의 성능을 높였습니다.
로컬 스토리지에는 다음과 같이 저장됩니다. 
<br><br>
<br><br>
<br><br>
> [Refactor] 카테고리 조회시 최초 한번만 하도록 성능개선

- frontend/src/components/common/BottomHeaderComponent.vue
- frontend/src/components/common/MiddleHeaderComponent.vue
- frontend/src/components/coupon/eventCouponComponent.vue
- frontend/src/components/coupon/myCouponListComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/stores/useCartStore.js
#361
1. 바로 구매하기 시 수정
2. 캐러셀 패딩 값
3. 헤더 선택시 active
4. 쿠폰 선택시 라우팅 
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] css 정리, 캐러셀 등 

- frontend/src/components/product/ProductComponent.vue
- frontend/src/components/product/ProductList4LayoutComponent.vue
- frontend/src/components/product/ProductList5LayoutComponent.vue
- frontend/src/pages/member/LoginPage.vue
- 상품 리스트 이미지 크기 고정
<br><br>
props 전달을 통해서 이미지 크기를 고정시켰습니다.
( 5Layout , 4Layout 각각 다른 크기로 고정)
<br><br>
<br><br>
<br><br>
> [Refactor] Props 전달을 통한, 이미지 크기 고정

- frontend/src/components/order/CartComponent.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
#371 
결제 페이지에서 등급 그리고 결제 정보 관련 에러 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 선물 결제 페이지 에러 수정

- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
#378
배송지 PathVariable 제대로 매핑되어있지 않은 문제 해결 
작업 TODO 삭제 
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 배송지 PathVariable 수정

- frontend/src/components/AdvertiseCarousel.vue
- frontend/src/pages/MainPage.vue
#num
- 메인 페이지 상단 광고 캐러셀 이미지 수정
- 메인 페이지 노출 상품들 이미지, 해시태그 수정
<br><br>
- 메인 페이지 상단 광고 캐러셀 이미지 수정
- 메인 페이지 노출 상품들 이미지, 해시태그 수정
- 상품 더보기 클릭시 연결되는 해시태그 번호 수정
<br><br>
<br><br>
<br><br>
> [Refac] 광고 캐러셀, 메인 페이지 노출 상품 이미지 수정

- frontend/src/pages/member/LoginPage.vue
- frontend/src/pages/member/LogoutPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useGiftStore.js
- 백엔드에서 token 문제로 인한 리다이렉트 신호가 오면, 로그아웃 처리
<br><br>
token문제로 인해 문제가 발생하면, 에러코드를 주도록 하였습니다.
프론트엔드는 해당 에러를 받으면 자연스럽게 로그아웃 처리를 하고, 로그인페이지로 이동하게 설정하였습니다. 
<br><br>
모든 axios 요청에 대해서 아래와 같은 예외처리가 필요로 됩니다.
대대적인 프론트 코드 수정이 이루어 질 예정입니다,, (해당 작업이 이루어질 땐 conflict 주의를 요합니다)
<br><br>
<br><br>
> [Feat] 로그아웃 리다이렉트 페이지 구현

- cicd/frontend/jenkins/jenkinsfile
- cicd/frontend/kubernetes/deployment-blue.yml
- cicd/frontend/kubernetes/deployment-green.yml
X
- 프론트 배포중 'Docker push' stage 제거
- 그에 맞춰 deployment.yml 수정
<br><br>
- 'Docker push' stage 제거하고 dist 폴더 내 파일을 전송하고, 그 파일로 deployment를 만드는걸로 수정
- Docker Image를 706com/frontend:latest 에서 nginx:alpine로 수정
- 전송받은 dist 폴더 내 파일로 볼륨을 만들어 deployment 생성
<br><br>
> [CI/CD] 'Docker push' stage 삭제

- cicd/frontend/jenkins/jenkinsfile
- cicd/frontend/kubernetes/deployment-blue.yml
- cicd/frontend/kubernetes/deployment-green.yml
X
- 이전 상태로 롤백
<br><br>
- 'Docker push' stage가 있는 상태로 롤백하였습니다.
<br><br>
> [CI/CD] 'Docker push' stage 롤백

- backend/src/main/java/com/synergy/backend/global/security/filter/LoginFilter.java
- backend/src/main/java/com/synergy/backend/global/security/filter/OAuth2Filter.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/service/RefreshTokenService.java
#393 
- Secure 설정 추가
- 
<br><br>
<br><br>
- Secure 설정이 추가 되었습니다.
해당 설정을 통해서, comegongbang 도메인으로 입장한 상태에서만 토큰(쿠키)이 발급됩니다. (공유기를 통해 들어오면 불가)
<br><br>
<br><br>
> [Refactor] 사이트 점검 및 기본기능에 대한 기능 개선 ( 진행중 )

- frontend/src/api/response.js
- frontend/src/components/member/DeliveryModalComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/vue.config.js
- 토큰 만료에 의한 자동 로그아웃 처리 인터셉터 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [Add,Refactor] 전역적으로 토큰 만료에 대한 로그아웃 요청을 처리할 수 있는 interceptor 추가 + 디자인 수정

- backend/src/main/java/com/synergy/backend/domain/likes/repository/LikesRepository.java
- backend/src/main/java/com/synergy/backend/domain/product/querydsl/ProductRepositoryCustomImpl.java
- backend/src/main/java/com/synergy/backend/domain/product/service/ProductService.java
#393
- 상품 리스트 조회할 때 like관련 n+1문제 해결
<br><br>
- 상품 리스트 조회할 때 like관련 n+1문제 해결
- member가 좋아요한 상품 idx 리스트 조회하는 메소드 이용해 해결
<br><br>
<br><br>
<br><br>
> [Fix] 상품 관련 수정

- frontend/src/components/product/ProductComponent.vue
#394 
- 할인률 수정
- 할인률 적용가 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [fix] 상품 컴포넌트 수정

- backend/src/main/java/com/synergy/backend/global/security/CustomUserDetailService.java
- backend/src/main/java/com/synergy/backend/global/security/OAuth2Service.java
- backend/src/main/java/com/synergy/backend/global/security/filter/OAuth2AuthenticationFailureHandler.java
#393 
- 소셜 로그인 주기적 오류를 잡기 위한 로깅 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] k8s sticky session 문제 해결을 위한 로그 작성

- frontend/src/components/order/CartComponent.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useCouponStore.js
- frontend/src/stores/useOrderStore.js
#394 
- 결제 페이지, 선물 결제 페이지 관련 에러 + 디테일 수정
<br><br>
- 결제 페이지 쿠폰 적용 추가
- 결제 페이지 할인률 적용 방식 변경 ( 상품 할인 -> 등급할인 -> 쿠폰할인)
- 선물 결제 페이지 쿠폰 적용 추가
- 선물 결제 페이지 할인률 적용 방식 변경 ( 상품 할인 -> 등급할인 -> 쿠폰할인)
- 백엔드로 결제 정보 넘길 때 쿠폰 Idx 같이 넘기도록 수정
- 결제 전에 사전 재고 검증 과정 추가 (전에는 백엔드만 구현돼있었음)
<br><br>
<br><br>
<br><br>
> [Fix] 결제 관련 페이지 점검 및 개선

- backend/src/main/java/com/synergy/backend/domain/coupon/repository/CouponRepository.java
- backend/src/main/java/com/synergy/backend/domain/grade/repository/GradeRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/controller/OrderController.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/CartDTO.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/CartProductListRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/CustomData.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/response/PreValidationRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/repository/CartRepository.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/CartService.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/OrderService.java
- backend/src/main/java/com/synergy/backend/domain/product/model/entity/ProductSubOptions.java
- backend/src/main/java/com/synergy/backend/domain/product/repository/ProductSubOptionsRepository.java
#393 
- 결제 관련 에러/디테일 수정
<br><br>
- 낙관적락을 비관적 락으로 수정
- 주석처리돼있던 결제 과정들 주석 해제
- 쿠폰 할인률 적용되도록 로직 추가
- 할인률 적용 방식 프론트에 따라 변경
<br><br>
<br><br>
<br><br>
> [Fix] 결제 관련 점검 및 수정

- backend/src/main/java/com/synergy/backend/domain/product/service/ElasticProductService.java
#396 
- es 검색 대상 수정
<br><br>
- 기존 es 검색 대상 product_name, atelier_name, category_name, hashtag_name, description
- description 삭제
<br><br>
<br><br>
<br><br>
> [Feat] 엘라스틱 서치 검색 대상에서 description 삭제

- backend/src/main/java/com/synergy/backend/domain/coupon/controller/CouponController.java
- backend/src/main/java/com/synergy/backend/domain/coupon/service/CouponService.java
- backend/src/main/java/com/synergy/backend/domain/queue/controller/QueueController.java
#num
customUserDetails.getIdx() == null 가 아니라
customUserDetails == null로 했어야 했는데 잘못된 예외처리 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 유저 NULL 처리 변경

- frontend/src/components/coupon/eventCouponComponent.vue
- frontend/src/components/coupon/myCouponListComponent.vue
#num
쿠폰 이미지 배포환경에서 안보이는 문제를 해결
이미지 주소 변경 
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 쿠폰 이미지 배포환경에서 안보이는 문제 

- backend/src/main/java/com/synergy/backend/domain/coupon/model/entity/MemberCoupon.java
- backend/src/main/java/com/synergy/backend/domain/coupon/repository/MemberCouponRepository.java
- backend/src/main/java/com/synergy/backend/domain/member/model/response/OrderListRes.java
- backend/src/main/java/com/synergy/backend/domain/orders/model/entity/Orders.java
- backend/src/main/java/com/synergy/backend/domain/orders/querydsl/OrderRepositoryCustomImpl.java
- backend/src/main/java/com/synergy/backend/domain/orders/service/OrderService.java
- backend/src/main/java/com/synergy/backend/domain/review/model/entity/Review.java
- backend/src/main/java/com/synergy/backend/domain/review/model/request/CreateReviewReq.java
- backend/src/main/java/com/synergy/backend/domain/review/model/response/WritableReviewRes.java
- backend/src/main/java/com/synergy/backend/domain/review/repository/ReviewRepository.java
- backend/src/main/java/com/synergy/backend/domain/review/service/ReviewService.java
#393 
- 주문 내역 반환 순서 변경
<br><br>
- 기존에는 오름차순으로 돼있던 주문 내역을 내림차순으로 변경
<br><br>
<br><br>
<br><br>
> [Fix] 주문 내역 반환 순서 변경

- frontend/src/components/error/NotFoundComponent.vue
404 페이지 "뒤로" 버튼 이벤트 
실제 뒤로 이동하도록 
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 404 페이지 "뒤로" 버튼 이벤트 

- backend/src/main/java/com/synergy/backend/domain/member/model/entity/Member.java
- backend/src/main/java/com/synergy/backend/domain/member/model/request/MemberSignupReq.java
#393 
- 회원가입시, 회원 기본 이미지 디폴트값 추가
- 
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor / Fix] 기본기능 백엔드 점검

- frontend/src/components/common/CountDown.vue
- frontend/src/components/sidebar/MyPageSideBarComponent.vue
- frontend/src/pages/MainPage.vue
#394 
-  메인페이지 상품 문구, 기간 설정
<br><br>
- 메인페이지 상품 이름과 핫딜 기간을 수정했습니다. 핫딜은 현재날짜 기준 +4일 부여하였습니다.
----
- 회원 기본프로필 적용하였습니다.
<br><br>
<br><br>
<br><br>
> [Design] 메인페이지 글씨, 핫딜 기간 수정

- backend/src/main/java/com/synergy/backend/domain/coupon/controller/CouponController.java
- backend/src/main/java/com/synergy/backend/domain/coupon/scheduler/CouponScheduler.java
- backend/src/main/java/com/synergy/backend/domain/grade/scheduler/GradeScheduler.java
- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
- backend/src/main/java/com/synergy/backend/domain/member/service/MemberEmailAuthService.java
- backend/src/main/java/com/synergy/backend/domain/orders/controller/OrderController.java
- backend/src/main/java/com/synergy/backend/domain/queue/service/QueueService.java
- backend/src/main/java/com/synergy/backend/global/Handler/QueueWebSocketHandler.java
- backend/src/main/java/com/synergy/backend/global/security/filter/LoginFilter.java
- backend/src/main/resources/application.yml
#415
1. 불필요 로그 삭제
2.실행할 스케줄러 시작 
3. 환경변수 설정
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 로그삭제 및 실행할 스케줄러 시작 

- frontend/src/components/product/ProductComponent.vue
#394 
- 상품 컴포넌트에 할인적용가 소수점 제거
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] 할인 적용가 소수점 제거

- frontend/src/components/coupon/eventCouponComponent.vue
- frontend/src/components/gift/GiftReceivedListComponent.vue
- frontend/src/components/member/AddAddressComponent.vue
- frontend/src/components/member/DeliveryComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/components/review/ReviewOfPurposeComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/product/CategoryProductListPage.vue
- frontend/src/stores/useAtelierStore.js
- frontend/src/stores/useCartStore.js
- frontend/src/stores/useCouponStore.js
- frontend/src/stores/useGiftStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useProductStore.js
- frontend/src/stores/useReviewStore.js
#417 
1. 사용 안하는 log 
2. 배송지 추가 검증 z-index 추가 
3. 상품 페이지 리다이렉트 
4. 선물하기 axios 주소 변경
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] 사용 안 하는 LOG, 배송지 추가 검증 z-index 등 

- backend/src/main/java/com/synergy/backend/domain/orders/service/OrderService.java
#393 
- 주문 오류 수정
<br><br>
- 쿠폰을 사용하지 않았을 때 처리를 하지 않아 나는 오류 수정
<br><br>
<br><br>
<br><br>
> [Fix] 주문 오류 수정

- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/stores/useOrderStore.js
#394 
결제 로딩창 추가
<br><br>
- 결제후에 주문 내역으로 리다이렉트될 때까지 시간이 오래 걸려서 로딩창을 추가했습니다.
<br><br>
<br><br>
<br><br>
> [Fix] 결제에 로딩창 추가

- frontend/src/components/order/CartComponent.vue
#421
1. 장바구니css
2. 요청메세지 버튼 활성화
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] 장바구니 헤더 css, 요청메세지 버튼 활성화

- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/stores/useCartStore.js
#394
- 결제 상품 목록에 주문 메세지 추가
<br><br>
<br><br>
<br><br>
<br><br>
> [fix] 결제 상품 목록에 주문 메세지 추가

- frontend/src/components/gift/GiftGiveDetailComponent.vue
- frontend/src/components/mypage/GradeComponent.vue
- frontend/src/components/order/CartComponent.vue
- frontend/src/components/order/OrderListComponent.vue
- frontend/src/components/product/ProductComponent.vue
- frontend/src/components/product/ProductDetailPaymentComponent.vue
- frontend/src/pages/payment/OrderPaymentPage.vue
- frontend/src/pages/payment/PresentPaymentPage.vue
- frontend/src/stores/useCartStore.js
- frontend/src/utils/formatPrice.js
#425 
1. formatPrice 설정 모든 곳에 적용
2. 선물하기 상호작용 에러 변경
선물하기에서 수량 변경, 요청메세지 등 상호작용 시 장바구니를 호출하는 코드를
변경해서 계속 선물하기 페이지를 띄워주게 
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] formatPrice 설정 모든 곳에, 선물하기 상호작용 에러 변경

- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/service/RefreshTokenService.java
- backend/src/main/java/com/synergy/backend/global/util/JwtUtil.java
#393 
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] RefreshToken API 요청 동시성 처리 (#393)

- backend/src/main/java/com/synergy/backend/global/security/jwt/service/RefreshTokenService.java
- backend/src/main/java/com/synergy/backend/global/util/JwtUtil.java
#393 
<br><br>
<br><br>
<br><br>
<br><br>
> [Fix] RefreshToken API 요청 동시성 처리

- backend/src/main/java/com/synergy/backend/domain/orders/repository/OrderRepository.java
String 타입 결제완료 문구 결제 완료로 변경
이후 Enum으로 통일 필요 
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] 등급 계산 시 쿼리 수정 

- backend/src/main/java/com/synergy/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/service/BlackListTokenService.java
- backend/src/main/java/com/synergy/backend/global/security/jwt/service/RefreshTokenService.java
(#393)
- 기존 key-value 형태에서, Set 자료구조 형태로 변경
<br><br>
<br><br>
<br><br>
<br><br>
> [Refactor] BlackList 토큰 Set 자료구조로 변경 

- backend/src/main/java/com/synergy/backend/domain/grade/service/GradeService.java
- backend/src/main/java/com/synergy/backend/global/InitData/InitDataWith300000.java
#434
1. 내 등급 조회에 문제가 발생
2. 로컬 DB, 서버 DB를 로컬 서버에 연결해서 각각 테스트해보니 정상작동
3. 등급 방어코드를 추가 구현 후 다시 테스트 
4. 정상작동 확인 후 push 
<br><br>
<br><br>
<br><br>
<br><br>
> [hotfix]등급 방어코드 추가 구현  #434

- frontend/src/components/AskCommentComponent.vue
- frontend/src/components/review/ProductReviewListComponent.vue
- frontend/src/pages/product/ProductDetailPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useAskCommentStore.js
#394 
- 후기 작성 리다이렉트 경로 수정
<br><br>
- 후기 작성을 누르면 없는 페이지로 이동하는 오류
<br><br>
<br><br>
<br><br>
> [Fix] 후기 작성 리다이렉트 경로 수정

- frontend/src/components/review/ProductReviewListComponent.vue
- frontend/src/components/sidebar/MyPageSideBarComponent.vue
#394
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [fix] 후기 작성 리다이렉트 변경 (#394)

- backend/src/main/java/com/synergy/backend/domain/coupon/service/CouponService.java
- backend/src/main/java/com/synergy/backend/domain/queue/service/QueueRedisService.java
- backend/src/main/java/com/synergy/backend/domain/queue/service/QueueService.java
쿠폰 자료형 오류로 Type 에러 해결 
프론트 예외처리를 위한 응답 재정비 
<br><br>
<br><br>
<br><br>
<br><br>
> [FIX] 쿠폰 자료형 오류.. 변경 및 예외처리

- frontend/src/components/coupon/eventCouponComponent.vue
- frontend/src/stores/useCouponStore.js
쿠폰 예외처리...
인텔리제이, vscode, 깃허브 죄다 안돼서 
2시부터 2시간동안 고생하다 올린 pr.. 
본다면 바로 머지부탁합니당
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 쿠폰 예외처리 

- backend/src/main/java/com/synergy/backend/domain/member/controller/MemberController.java
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 로컬스토리지에는 남아있으나, 토큰 값이 없는 유저 로그아웃 유도 구현

- frontend/src/api/response.js
- frontend/src/router/index.js
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 로컬스토리지에는 남아있으나, 토큰 값이 없는 유저 로그아웃 처리

- README.md
<br><br>
<br><br>
<br><br>
<br><br>
> [Docs] readme 수정

- backend/README.md
- cicd/README.md
#num
프론트, 백, CICD 리드미 추가
<br><br>
> frontend/backend/cicd 리드미 추가

- frontend/src/stores/useProductStore.js
#382 
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] 키워드 검색에 Elasticsearch 적용

- backend/src/main/java/com/synergy/backend/domain/product/service/ElasticProductService.java
#num
- ~~ 기능 개발
- ~~ 내역 수정
<br><br>
<br><br>
<br><br>
<br><br>
> [Feat] elasticsearch에 초성 검색 추가 
